<?php
namespace App\Services;
use App\Models\Order;use App\Models\User;use Illuminate\Support\Carbon;use Illuminate\Support\Str;
class MembershipService{
 public const TIERS=['bronze'=>['label'=>'Hạng Đồng','minimum'=>0,'rate'=>5],'gold'=>['label'=>'Hạng Vàng','minimum'=>5000000,'rate'=>7],'diamond'=>['label'=>'Hạng Kim cương','minimum'=>20000000,'rate'=>10]];
 public function totalSpent(User$user):int{$emails=Order::query()->where(fn($q)=>$q->where('user_id',$user->id)->orWhereRaw('LOWER(customer_email)=?', [Str::lower(trim((string)$user->email))]))->whereNotNull('customer_email')->pluck('customer_email')->map(fn($v)=>Str::lower(trim((string)$v)))->filter()->unique()->values()->all();$emails=array_values(array_unique([...$emails,Str::lower(trim((string)$user->email))]));$phones=Order::query()->where(fn($q)=>$q->where('user_id',$user->id)->orWhere('customer_phone',trim((string)$user->phone)))->whereNotNull('customer_phone')->pluck('customer_phone')->map(fn($v)=>trim((string)$v))->filter()->unique()->values()->all();$phones=array_values(array_unique([...$phones,trim((string)$user->phone)]));return(int)Order::query()->whereIn('status',['Đã duyệt','Đang giao','Đã giao'])->where(function($q)use($emails,$phones,$user){$q->where('user_id',$user->id);if($emails)$q->orWhereIn('customer_email',$emails);if($phones)$q->orWhereIn('customer_phone',$phones);})->sum('total');}
 public function tier(User$user):string{$total=$this->totalSpent($user);return$total>=20000000?'diamond':($total>=5000000?'gold':'bronze');}
 public function weeklyCoupons(User$user,?Carbon$now=null):array{$now??=now();if(!in_array($now->dayOfWeek,[Carbon::SATURDAY,Carbon::SUNDAY],true))return[];$slot=intdiv((int)$now->hour,6);$start=$now->copy()->startOfDay()->addHours($slot*6);$end=$start->copy()->addHour();if($now->greaterThanOrEqualTo($end))return[];$tier=$this->tier($user);$types=['linh-kien','laptop','phu-kien'];$seed=$start->format('Y-m-d-H').'|'.$tier.'|techstore';$offset=hexdec(substr(sha1($seed),0,6))%3;$selected=[$types[$offset],$types[($offset+1)%3]];$discount=self::TIERS[$tier]['rate'];return array_map(fn(string$type)=>['code'=>'TS'.strtoupper(substr($type,0,2)).strtoupper(substr(sha1($seed.'|'.$type),0,5)),'type'=>$type,'discount'=>$discount,'starts_at'=>$start->toIso8601String(),'ends_at'=>$end->toIso8601String(),'label'=>$type==='laptop'?'Laptop':($type==='linh-kien'?'Linh kiện':'Phụ kiện')],$selected);}
 public function specialEvents(User$user,?Carbon$now=null):array{$now??=now();if(!in_array(strtolower((string)$user->member_type),['student','teacher'],true))return[];$year=$now->year;return[['date'=>"{$year}-09-05",'title'=>'Tựu trường / Khai giảng','code'=>'TSEDU'.substr((string)$year,-2),'note'=>'Ưu đãi Student/Teacher quanh ngày 5/9.'],['date'=>"{$year}-11-20",'title'=>'Ngày Nhà giáo Việt Nam','code'=>'TSGVN'.substr((string)$year,-2),'note'=>'Ưu đãi dành cho Teacher và chương trình giáo dục.']];}
 public function couponFor(User$user,string$code,?Carbon$now=null):?array{$now??=now();$normalized=strtoupper(trim($code));foreach($this->weeklyCoupons($user,$now)as$coupon)if($coupon['code']===$normalized)return$coupon;foreach($this->specialEvents($user,$now)as$event)if($event['code']===$normalized&&$now->isSameDay(Carbon::parse($event['date'])))return['code'=>$normalized,'type'=>'education','discount'=>self::TIERS[$this->tier($user)]['rate']+2,'starts_at'=>$event['date'].'T00:00:00+07:00','ends_at'=>$event['date'].'T23:59:59+07:00','label'=>$event['title']];return null;}
}
