<?php
namespace App\Http\Controllers\Settings;
use App\Http\Requests\Settings\ProfileDeleteRequest;use App\Http\Requests\Settings\ProfileUpdateRequest;use App\Models\Order;use App\Services\MembershipService;use Illuminate\Contracts\Auth\MustVerifyEmail;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Validation\Rules\Password;use Inertia\Inertia;use Inertia\Response;use Laravel\Fortify\Features;
class ProfileController
{
 public function edit(Request$request,MembershipService$membership):Response{$user=$request->user();$orders=Order::query()->where('user_id',$user->id)->with('items')->latest('created_at')->get()->map(fn(Order$order):array=>['id'=>$order->id,'code'=>$order->code,'createdAt'=>optional($order->created_at)->toISOString(),'customer'=>['name'=>$order->customer_name,'phone'=>$order->customer_phone,'email'=>$order->customer_email,'address'=>$order->customer_address,'note'=>$order->note],'vatInvoice'=>['requested'=>(bool)$order->vat_invoice_requested,'companyName'=>$order->vat_company_name,'taxCode'=>$order->vat_tax_code,'address'=>$order->vat_address,'email'=>$order->vat_email,'rate'=>(float)$order->vat_rate,'amount'=>$order->vat_amount],'items'=>$order->items->map(fn($item):array=>['id'=>$item->product_id??$item->id,'name'=>$item->name,'price'=>(int)$item->price,'image'=>$item->image,'quantity'=>(int)$item->quantity])->values()->all(),'subtotal'=>(int)$order->subtotal,'shipping'=>(int)$order->shipping,'totalShipping'=>(int)$order->total_shipping,'total'=>(int)$order->total,'payment'=>$order->payment,'couponCode'=>$order->coupon_code,'discount'=>(int)$order->discount,'paypalOrderId'=>$order->paypal_order_id,'status'=>$order->status,'cancelledAt'=>optional($order->cancelled_at)->toISOString(),'returnedAt'=>optional($order->returned_at)->toISOString()])->values()->all();$tier=$membership->tier($user);$tierMeta=MembershipService::TIERS[$tier];return Inertia::render('settings/Profile',['mustVerifyEmail'=>$user instanceof MustVerifyEmail,'status'=>$request->session()->get('status'),'passwordRules'=>Password::defaults()->toPasswordRulesString(),'canManageTwoFactor'=>Features::canManageTwoFactorAuthentication(),'canManagePasskeys'=>Features::canManagePasskeys(),'twoFactorEnabled'=>Features::canManageTwoFactorAuthentication()?$user->hasEnabledTwoFactorAuthentication():false,'requiresConfirmation'=>Features::canManageTwoFactorAuthentication()?Features::optionEnabled(Features::twoFactorAuthentication(),'confirm'):false,'passkeys'=>Features::canManagePasskeys()?$user->passkeys()->select(['id','name','credential','created_at','last_used_at'])->latest()->get()->map(fn($p)=>['id'=>$p->id,'name'=>$p->name,'authenticator'=>$p->authenticator,'created_at_diff'=>$p->created_at->diffForHumans(),'last_used_at_diff'=>$p->last_used_at?->diffForHumans()])->values()->all():[],'orders'=>$orders,'membership'=>['tier'=>$tier,'label'=>$tierMeta['label'],'discountRate'=>$tierMeta['rate'],'memberType'=>$user->member_type]]);}
 public function update(ProfileUpdateRequest$request):RedirectResponse{$data=$request->validated();unset($data['email']);$request->user()->fill($data)->save();return to_route('profile.edit')->with('status','profile-updated');}
 public function destroy(ProfileDeleteRequest$request):RedirectResponse{$user=$request->user();Auth::logout();$user->delete();$request->session()->invalidate();$request->session()->regenerateToken();return redirect('/');}
}
