<?php
namespace App\Http\Controllers;
use App\Models\AccountDeletionOtp;use App\Models\AccountDeletionRequest;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Facades\Mail;use Inertia\Inertia;use Inertia\Response;
class AccountDeletionController extends Controller
{
 public function show(Request$request):Response{return Inertia::render('settings/AccountDeletion',['status'=>session('status')]);}
 public function sendOtp(Request$request):RedirectResponse{$user=$request->user();$code=(string)random_int(100000,999999);AccountDeletionOtp::query()->where('user_id',$user->id)->delete();$otp=AccountDeletionOtp::create(['user_id'=>$user->id,'code_hash'=>Hash::make($code),'expires_at'=>now()->addMinutes(10)]);$request->session()->put('account_deletion_otp_id',$otp->id);Mail::raw("Mã OTP xác nhận yêu cầu xóa tài khoản TechStore: {$code}\n\nMã có hiệu lực 10 phút.",fn($m)=>$m->to($user->email)->subject('OTP yêu cầu xóa tài khoản TechStore'));return back()->with('status','OTP đã được gửi đến Email.');}
 public function verify(Request$request):RedirectResponse{$id=$request->session()->get('account_deletion_otp_id');$otp=$id?AccountDeletionOtp::query()->whereKey($id)->where('user_id',$request->user()->id)->first():null;$data=$request->validate(['code'=>['required','digits:6']]);abort_unless($otp&&!$otp->verified_at&&!$otp->expires_at->isPast()&&$otp->attempts<5,422,'Phiên OTP không còn hợp lệ.');if(!Hash::check($data['code'],$otp->code_hash)){$otp->increment('attempts');return back()->withErrors(['code'=>'OTP không chính xác.']);}$otp->update(['verified_at'=>now()]);AccountDeletionRequest::query()->where('user_id',$request->user()->id)->where('status','pending')->delete();AccountDeletionRequest::create(['user_id'=>$request->user()->id,'status'=>'pending']);$request->session()->forget('account_deletion_otp_id');return back()->with('status','Đã gửi yêu cầu xóa tài khoản đến Admin phê duyệt.');}
 public function adminIndex():Response{return Inertia::render('admin/AccountDeletionRequests',['requests'=>AccountDeletionRequest::query()->where('status','pending')->with('user:id,name,email')->latest()->get()->map(fn(AccountDeletionRequest$r)=>['id'=>$r->id,'user'=>$r->user?->only(['id','name','email']),'createdAt'=>$r->created_at?->toIso8601String()])]);}
 public function approve(Request$request,AccountDeletionRequest$deletionRequest):RedirectResponse{abort_unless($request->user()->isAdmin(),403);abort_unless($deletionRequest->status==='pending',422,'Yêu cầu đã được xử lý.');$user=$deletionRequest->user;$deletionRequest->update(['status'=>'approved','approved_by'=>$request->user()->id,'approved_at'=>now()]);$user->delete();return to_route('admin.account-deletion-requests')->with('success','Đã phê duyệt xóa tài khoản.');}
 public function reject(Request$request,AccountDeletionRequest$deletionRequest):RedirectResponse{abort_unless($request->user()->isAdmin(),403);$deletionRequest->update(['status'=>'rejected','approved_by'=>$request->user()->id,'rejected_at'=>now(),'rejection_reason'=>$request->string('reason')->toString()]);return back()->with('success','Đã từ chối yêu cầu xóa tài khoản.');}
}
