<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';

type Admin={id:number;name:string;email:string;is_active:boolean;admin_permissions:string[]|null;created_at:string};
type Permission={ [key:string]: string };
const props=defineProps<{administrators:{data:Admin[];total:number};permissions:Permission}>();
const show=ref(false);const editing=ref<Admin|null>(null);const form=ref({name:'',email:'',password:'',admin_permissions:[] as string[],is_active:true});
const permissionKeys=Object.keys(props.permissions);
function reset(){editing.value=null;form.value={name:'',email:'',password:'',admin_permissions:[],is_active:true};show.value=true}
function edit(a:Admin){editing.value=a;form.value={name:a.name,email:a.email,password:'',admin_permissions:a.admin_permissions??permissionKeys,is_active:a.is_active};show.value=true}
function toggleAll(){form.value.admin_permissions=form.value.admin_permissions.length===permissionKeys.length?[]:[...permissionKeys]}
function save(){const payload={name:form.value.name,email:form.value.email,password:form.value.password||undefined,admin_permissions:form.value.admin_permissions,is_active:form.value.is_active};editing.value?router.patch(`/admin/administrators/${editing.value.id}`,payload,{onSuccess:()=>show.value=false}):router.post('/admin/administrators',payload,{onSuccess:()=>show.value=false})}
function toggle(a:Admin){router.patch(`/admin/administrators/${a.id}/toggle`,{})}
function remove(a:Admin){if(confirm(`Xóa quản trị viên ${a.name}?`))router.delete(`/admin/administrators/${a.id}`)}
function permissionText(a:Admin){return a.name==='admin'?'Toàn quyền':`${(a.admin_permissions??[]).length}/${permissionKeys.length} quyền`}
</script>
<template>
<div class="admin-page">
 <div class="admin-page-head"><div><div class="admin-kicker">HỆ THỐNG</div><h1>Quản trị viên</h1><p>Tạo tài khoản quản trị và phân quyền theo từng khu vực của hệ thống.</p></div><button class="btn btn-primary" @click="reset"><i class="bi bi-person-plus-fill me-2"/>Tạo quản trị viên</button></div>
 <div class="admin-panel overflow-hidden"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Quản trị viên</th><th>Phân quyền</th><th>Trạng thái</th><th>Ngày tạo</th><th class="text-end">Thao tác</th></tr></thead><tbody>
 <tr v-for="a in props.administrators.data" :key="a.id"><td><div class="d-flex align-items-center gap-3"><div class="admin-avatar"><i class="bi bi-shield-lock-fill"/></div><div><div class="fw-bold">{{a.name}} <span v-if="a.name==='admin'" class="root-badge">GỐC</span></div><div class="small text-secondary">{{a.email}}</div></div></div></td><td><span class="permission-badge"><i class="bi bi-key-fill me-1"/>{{permissionText(a)}}</span></td><td><span :class="['badge',a.is_active?'text-bg-success':'text-bg-secondary']">{{a.is_active?'Đang hoạt động':'Đã khóa'}}</span></td><td>{{new Date(a.created_at).toLocaleDateString('vi-VN')}}</td><td class="text-end"><div class="btn-group btn-group-sm"><button class="btn btn-outline-primary" @click="edit(a)"><i class="bi bi-pencil"/></button><button v-if="a.name!=='admin'" class="btn btn-outline-secondary" @click="toggle(a)"><i :class="['bi',a.is_active?'bi-lock':'bi-unlock']"/></button><button v-if="a.name!=='admin'" class="btn btn-outline-danger" @click="remove(a)"><i class="bi bi-trash"/></button></div></td></tr>
 <tr v-if="!props.administrators.data.length"><td colspan="5" class="text-center py-5 text-secondary">Chưa có quản trị viên.</td></tr>
 </tbody></table></div></div>
 <div v-if="show" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content border-0 shadow-lg admin-admin-modal"><div class="modal-header"><div><div class="modal-kicker">QUẢN TRỊ HỆ THỐNG</div><h5 class="mb-0">{{editing?'Cập nhật':'Tạo'}} quản trị viên</h5></div><button class="btn-close" @click="show=false"/></div><form @submit.prevent="save"><div class="modal-body">
  <div class="row g-3"><div class="col-md-6"><label class="form-label">Tên tài khoản</label><input v-model="form.name" class="form-control" required :disabled="editing?.name==='admin'"/><div class="form-hint">Dùng làm tên đăng nhập quản trị.</div></div><div class="col-md-6"><label class="form-label">Email</label><input v-model="form.email" type="email" class="form-control" required/></div><div class="col-md-6"><label class="form-label">Mật khẩu <span v-if="editing" class="text-secondary">(bỏ trống nếu không đổi)</span></label><input v-model="form.password" type="password" class="form-control" :required="!editing" minlength="8"/></div><div class="col-md-6 d-flex align-items-end"><div class="form-check form-switch pb-2"><input id="adminActive" v-model="form.is_active" class="form-check-input" type="checkbox" :disabled="editing?.name==='admin'"/><label for="adminActive" class="form-check-label fw-semibold">Tài khoản đang hoạt động</label></div></div></div>
  <div class="permission-box mt-4"><div class="permission-head"><div><h6>Phân quyền truy cập</h6><p>Chỉ những chức năng được chọn mới được phép truy cập.</p></div><button type="button" class="btn btn-sm btn-outline-primary" @click="toggleAll">{{form.admin_permissions.length===permissionKeys.length?'Bỏ chọn tất cả':'Chọn tất cả'}}</button></div><div class="row g-2"><div v-for="key in permissionKeys" :key="key" class="col-md-6"><label class="permission-item"><input v-model="form.admin_permissions" type="checkbox" :value="key" :disabled="editing?.name==='admin'"/><span class="permission-icon"><i class="bi bi-check2"/></span><span><strong>{{props.permissions[key]}}</strong><small>Quyền truy cập {{props.permissions[key].toLowerCase()}}</small></span></label></div></div><div v-if="editing?.name==='admin'" class="root-note"><i class="bi bi-shield-fill-check"/> Tài khoản <strong>admin</strong> là tài khoản gốc và luôn có toàn quyền.</div></div>
 </div><div class="modal-footer"><button type="button" class="btn btn-light" @click="show=false">Hủy</button><button class="btn btn-primary px-4">{{editing?'Lưu thay đổi':'Tạo tài khoản'}}</button></div></form></div></div></div>
</div>
</template>
<style scoped>
.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}.admin-avatar{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;color:#4338ca;background:linear-gradient(135deg,#eef2ff,#e0e7ff)}.root-badge{margin-left:5px;padding:3px 6px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:7px;font-weight:900;vertical-align:middle}.permission-badge{display:inline-flex;align-items:center;padding:6px 9px;border-radius:999px;background:#f5f3ff;color:#5b21b6;font-size:.7rem;font-weight:800}.admin-modal-backdrop{background:rgba(15,23,42,.5);backdrop-filter:blur(4px)}.admin-admin-modal{border-radius:20px;overflow:hidden}.modal-kicker{color:#4f46e5;font-size:8px;font-weight:900;letter-spacing:.14em;margin-bottom:3px}.permission-box{padding:16px;border:1px solid #e5e7eb;border-radius:16px;background:#f8fafc}.permission-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.permission-head h6{margin:0;font-weight:900}.permission-head p{margin:3px 0 0;color:#667085;font-size:.72rem}.permission-item{display:flex;align-items:center;gap:10px;padding:11px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;cursor:pointer;transition:.15s}.permission-item:hover{border-color:#bfdbfe;background:#fbfdff}.permission-item input{position:absolute;opacity:0}.permission-icon{display:grid;flex:0 0 24px;width:24px;height:24px;place-items:center;border:1px solid #cbd5e1;border-radius:7px;color:transparent}.permission-item input:checked~.permission-icon{border-color:#4f46e5;background:#4f46e5;color:#fff}.permission-item span:last-child{display:flex;flex-direction:column}.permission-item strong{font-size:.78rem}.permission-item small{color:#98a2b3;font-size:.65rem;margin-top:2px}.form-hint{margin-top:4px;color:#98a2b3;font-size:.65rem}.root-note{display:flex;align-items:center;gap:7px;margin-top:12px;padding:9px 11px;border-radius:10px;background:#eef2ff;color:#4338ca;font-size:.72rem}
</style>
