<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';
type Admin={id:number;name:string;email:string;is_active:boolean;admin_permissions:string[]|null;created_at:string};
type Employee={id:number;name:string;email:string;phone:string|null;role:string;role_label:string;is_active:boolean;approval_status:string;created_at:string;creator:{id:number;name:string}|null};
const props=defineProps<{administrators:{data:Admin[];total:number};permissions:Record<string,string>;employeeApprovals:Employee[];seniorStaff:Employee[];staff:Employee[]}>();
const show=ref(false),security=ref(false),mode=ref<'senior'|'staff'|'admin'>('senior');
const editingAdmin=ref<Admin|null>(null),editingSenior=ref<Employee|null>(null),editingEmployee=ref<Employee|null>(null);
const securityAction=ref<'create'|'edit'|'toggle'|'delete'>('create'),securityPassword=ref('');const pending=ref<()=>void>(()=>{});
const form=ref({name:'',email:'',phone:'',password:'',admin_permissions:[] as string[],is_active:true,role:'seo_staff'});
const staffRoles=[{value:'seo_staff',label:'Nhân viên SEO'},{value:'advertising_staff',label:'Nhân viên Quảng Cáo'},{value:'content_staff',label:'Nhân viên sáng tạo nội dung'},{value:'chat_hotline_staff',label:'Nhân viên trực chat/hotline'},{value:'complaint_staff',label:'Nhân viên xử lý khiếu nại'},{value:'inventory_staff',label:'Nhân viên quản lý kho'},{value:'sales_staff',label:'Nhân viên bán hàng'},{value:'sales_coordinator_staff',label:'Nhân viên điều phối giao hàng'},{value:'technical_staff',label:'Nhân viên kỹ thuật'}];
function askSecurity(action:'create'|'edit'|'toggle'|'delete',fn:()=>void){securityAction.value=action;securityPassword.value='';pending.value=fn;security.value=true}
function closeSecurity(){security.value=false;securityPassword.value=''}
function confirmSecurity(){if(!securityPassword.value.trim())return;const fn=pending.value;security.value=false;fn()}
function openSenior(){editingSenior.value=null;editingAdmin.value=null;editingEmployee.value=null;mode.value='senior';form.value={name:'',email:'',phone:'',password:'',admin_permissions:[],is_active:true,role:'senior_staff'};askSecurity('create',()=>show.value=true)}
function openStaff(){editingSenior.value=null;editingAdmin.value=null;editingEmployee.value=null;mode.value='staff';form.value={name:'',email:'',phone:'',password:'',admin_permissions:[],is_active:true,role:staffRoles[0].value};show.value=true}
function editAdmin(a:Admin){editingAdmin.value=a;editingSenior.value=null;editingEmployee.value=null;mode.value='admin';form.value={name:a.name,email:a.email,phone:'',password:'',admin_permissions:a.admin_permissions??Object.keys(props.permissions),is_active:a.is_active,role:'admin'};show.value=true}
function editSenior(a:Employee){editingSenior.value=a;editingAdmin.value=null;editingEmployee.value=null;mode.value='senior';form.value={name:a.name,email:a.email,phone:a.phone??'',password:'',admin_permissions:[],is_active:a.is_active,role:'senior_staff'};askSecurity('edit',()=>show.value=true)}
function editEmployee(a:Employee){editingEmployee.value=a;editingSenior.value=null;editingAdmin.value=null;mode.value='staff';form.value={name:a.name,email:a.email,phone:a.phone??'',password:'',admin_permissions:[],is_active:a.is_active,role:a.role};show.value=true}
function save(){
 if(mode.value==='admin'&&editingAdmin.value){router.patch(`/admin/administrators/${editingAdmin.value.id}`,{name:form.value.name,email:form.value.email,password:form.value.password||undefined,admin_permissions:form.value.admin_permissions,is_active:form.value.is_active},{onSuccess:()=>show.value=false});return}
 if(editingSenior.value){router.patch(`/admin/administrators/senior-staff/${editingSenior.value.id}`,{name:form.value.name,email:form.value.email,phone:form.value.phone,password:form.value.password||undefined,is_active:form.value.is_active,admin_password:securityPassword.value},{onSuccess:()=>show.value=false});return}
 if(editingEmployee.value){router.patch(`/admin/employees/${editingEmployee.value.id}`,{name:form.value.name,email:form.value.email,phone:form.value.phone,password:form.value.password||undefined,role:form.value.role},{onSuccess:()=>show.value=false});return}
 if(mode.value==='senior'){router.post('/admin/administrators/senior-staff',{name:form.value.name,email:form.value.email,phone:form.value.phone,password:form.value.password,admin_password:securityPassword.value},{onSuccess:()=>show.value=false});return}
 router.post('/admin/administrators/employees',{name:form.value.name,email:form.value.email,phone:form.value.phone,password:form.value.password,role:form.value.role},{onSuccess:()=>show.value=false});
}
function toggleSenior(a:Employee){askSecurity('toggle',()=>router.patch(`/admin/administrators/senior-staff/${a.id}/toggle`,{admin_password:securityPassword.value}))}
function removeSenior(a:Employee){askSecurity('delete',()=>router.delete(`/admin/administrators/senior-staff/${a.id}`,{data:{admin_password:securityPassword.value}}))}
function approve(a:Employee){router.patch(`/admin/employees/${a.id}/approve`,{})}
function removeEmployee(a:Employee){if(confirm(`Xóa nhân viên ${a.name}?`))router.delete(`/admin/employees/${a.id}`)}
function permissionText(a:Admin){return a.name==='admin'?'Toàn quyền':`${(a.admin_permissions??[]).length}/${Object.keys(props.permissions).length} quyền`}
function statusLabel(a:Employee){return a.approval_status==='pending'?'Chờ phê duyệt':a.approval_status==='rejected'?'Từ chối':a.is_active?'Đang hoạt động':'Đã khóa'}
function forgotAdminPassword(){router.get('/admin/administrator/password/forgot')}
function editAdminEmail(){router.get('/admin/administrator/email/edit')}
</script>
<template><div class="admin-page">
<div class="admin-page-head"><div><div class="admin-kicker">HỆ THỐNG</div><h1>Quản trị viên</h1><p>Quản lý tài khoản quản trị, Nhân viên cấp cao và toàn bộ nhân viên.</p></div><div class="page-actions"><button class="btn btn-primary" @click="openSenior">Tạo tài khoản Nhân viên cấp cao</button><button class="btn btn-outline-primary" @click="openStaff">Tạo nhân viên</button></div></div>
<section class="list-section"><div class="section-heading"><div><span class="section-kicker">PHÊ DUYỆT NHÂN SỰ</span><h2>Nhân viên chờ phê duyệt</h2><p>Nhân viên do Nhân viên cấp cao tạo phải được phê duyệt trước khi đăng nhập.</p></div><span class="section-count">{{props.employeeApprovals.length}} chờ duyệt</span></div><div class="admin-panel"><div v-if="props.employeeApprovals.length" class="approval-list"><div v-for="item in props.employeeApprovals" :key="item.id" class="approval-row"><div><strong>{{item.name}}</strong><small>{{item.email}}<span v-if="item.phone"> • {{item.phone}}</span></small></div><span class="role-chip">{{item.role_label}}</span><span>{{item.creator?.name??'Không xác định'}}</span><div class="approval-actions"><button class="btn btn-sm btn-outline-primary" @click="editEmployee(item)">Sửa</button><button class="btn btn-sm btn-outline-danger" @click="removeEmployee(item)">Xóa</button><button class="btn btn-sm btn-success" @click="approve(item)">Phê duyệt</button></div></div></div><div v-else class="empty-state">Không có nhân viên chờ phê duyệt.</div></div></section>
<section class="list-section"><div class="section-heading"><div><span class="section-kicker">QUẢN TRỊ VIÊN</span><h2>Quản trị viên</h2></div></div><div class="admin-panel overflow-hidden"><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Tài khoản</th><th>Phân quyền</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody><tr v-for="item in props.administrators.data" :key="item.id"><td><strong>{{item.name}}</strong><small>{{item.email}}</small></td><td><span class="role-chip">{{permissionText(item)}}</span></td><td><span :class="['employee-status',item.is_active?'active':'inactive']">{{item.is_active?'Đang hoạt động':'Đã khóa'}}</span></td><td>{{new Date(item.created_at).toLocaleDateString('vi-VN')}}</td><td><div class="d-flex gap-1 flex-wrap"><template v-if="item.name==='admin'"><button class="btn btn-sm btn-outline-warning" @click="forgotAdminPassword">Quên mật khẩu</button><button class="btn btn-sm btn-outline-secondary" @click="editAdminEmail">Sửa lại Email</button></template></div></td></tr></tbody></table></div></div></section>
<section class="list-section"><div class="section-heading"><div><span class="section-kicker">NHÂN SỰ</span><h2>Nhân viên cấp cao</h2><p>Thêm, sửa, xóa, khóa và mở khóa đều yêu cầu mật khẩu Quản trị viên.</p></div><span class="section-count">{{props.seniorStaff.length}} tài khoản</span></div><div class="admin-panel overflow-hidden"><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Nhân viên cấp cao</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody><tr v-for="item in props.seniorStaff" :key="item.id"><td><strong>{{item.name}}</strong><small>{{item.email}}<span v-if="item.phone"> • {{item.phone}}</span></small></td><td><span class="role-chip">Nhân viên cấp cao</span></td><td><span :class="['employee-status',item.is_active?'active':'inactive']">{{item.is_active?'Đang hoạt động':'Đã khóa'}}</span></td><td>{{new Date(item.created_at).toLocaleDateString('vi-VN')}}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary me-1" @click="editSenior(item)">Sửa</button><button class="btn btn-sm btn-outline-secondary me-1" @click="toggleSenior(item)">{{item.is_active?'Khóa':'Mở khóa'}}</button><button class="btn btn-sm btn-outline-danger" @click="removeSenior(item)">Xóa</button></td></tr><tr v-if="!props.seniorStaff.length"><td colspan="5" class="empty-state">Chưa có tài khoản Nhân viên cấp cao.</td></tr></tbody></table></div></div></section>
<section class="list-section"><div class="section-heading"><div><span class="section-kicker">NHÂN SỰ</span><h2>Nhân viên</h2><p>Các tài khoản nhân viên được Quản trị viên tạo trực tiếp hoặc do Nhân viên cấp cao tạo.</p></div><span class="section-count">{{props.staff.length}} tài khoản</span></div><div class="admin-panel overflow-hidden"><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Nhân viên</th><th>Chức vụ</th><th>Người tạo</th><th>Trạng thái</th><th>Ngày tạo</th></tr></thead><tbody><tr v-for="item in props.staff" :key="item.id"><td><strong>{{item.name}}</strong><small>{{item.email}}</small></td><td><span class="role-chip">{{item.role_label}}</span></td><td>{{item.creator?.name??'Hệ thống'}}</td><td><span :class="['employee-status',item.approval_status==='pending'?'pending':item.approval_status==='rejected'?'rejected':item.is_active?'active':'inactive']">{{statusLabel(item)}}</span></td><td>{{new Date(item.created_at).toLocaleDateString('vi-VN')}}</td></tr><tr v-if="!props.staff.length"><td colspan="5" class="empty-state">Chưa có tài khoản nhân viên.</td></tr></tbody></table></div></div></section>
<div v-if="show" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content admin-modal"><div class="modal-header"><div><div class="modal-kicker">HỒ SƠ NHÂN SỰ</div><h5>{{editingAdmin?'Cập nhật quản trị viên':editingSenior?'Sửa Nhân viên cấp cao':editingEmployee?'Sửa nhân viên':mode==='senior'?'Tạo tài khoản Nhân viên cấp cao':'Tạo nhân viên'}}</h5></div><button class="btn-close" @click="show=false"/></div><form @submit.prevent="save"><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">{{mode==='admin'?'Tên tài khoản':'Họ tên'}}</label><input v-model="form.name" class="form-control" required/></div><div class="col-md-6"><label class="form-label">Email</label><input v-model="form.email" type="email" class="form-control" required/></div><div v-if="mode!=='admin'" class="col-md-6"><label class="form-label">Số điện thoại</label><input v-model="form.phone" class="form-control"/></div><div class="col-md-6"><label class="form-label">Mật khẩu tài khoản <span v-if="editingSenior||editingEmployee">(bỏ trống nếu không đổi)</span></label><input v-model="form.password" type="password" class="form-control" :required="!editingSenior&&!editingEmployee&&mode!=='admin'" minlength="8"/></div><div v-if="mode==='staff'" class="col-12"><label class="form-label">Chức vụ của nhân viên</label><select v-model="form.role" class="form-select"><option v-for="o in staffRoles" :key="o.value" :value="o.value">{{o.label}}</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="show=false">Hủy</button><button class="btn btn-primary">{{editingAdmin||editingSenior||editingEmployee?'Lưu thay đổi':mode==='senior'?'Tạo tài khoản Nhân viên cấp cao':'Tạo nhân viên'}}</button></div></form></div></div></div>
<div v-if="security" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered"><form class="modal-content security-modal" @submit.prevent="confirmSecurity"><div class="modal-header"><div><div class="modal-kicker">BẢO MẬT TECHSTORE</div><h5>Nhập mật khẩu Quản trị viên</h5></div><button type="button" class="btn-close" @click="closeSecurity"/></div><div class="modal-body"><div class="security-icon"><i class="bi bi-shield-lock-fill"/></div><p>{{securityAction==='create'?'Xác thực để tạo tài khoản Nhân viên cấp cao.':securityAction==='edit'?'Xác thực để sửa tài khoản Nhân viên cấp cao.':securityAction==='toggle'?'Xác thực để khóa hoặc mở khóa tài khoản.':'Xác thực để xóa tài khoản.'}}</p><label class="form-label">Mật khẩu Quản trị viên</label><input v-model="securityPassword" type="password" class="form-control form-control-lg" required minlength="8" autocomplete="current-password" autofocus/></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="closeSecurity">Hủy</button><button class="btn btn-primary" type="submit">Xác nhận</button></div></form></div></div>
</div></template>
<style scoped>
.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin... (truncated) 
