<script setup lang="ts">
import { Form } from '@inertiajs/vue3';
import { computed } from 'vue';
type U={id:number;name:string;email:string;phone?:string;is_active:boolean};type R={id:number;name:string;email:string;phone?:string;requester?:{name:string};createdAt:string};
const p=defineProps<{role:string;roleLabel:string;users:{data:U[]};pendingRequests:R[]}>();
const desc=computed(()=>({sales:'Bán hàng và vận hành đơn hàng.',technical:'Sản phẩm, tồn kho và hỗ trợ kỹ thuật.',customer_service:'Chăm sóc khách hàng và hỗ trợ sau bán.'}[p.role]??''));
</script>
<template>
<div class="admin-page"><header class="head"><div><span>NHÂN SỰ · {{roleLabel.toUpperCase()}}</span><h1>{{roleLabel}}</h1><p>{{desc}}</p></div></header>
<section class="panel"><div class="panel-title"><div><strong>Tài khoản {{roleLabel.toLowerCase()}}</strong><small>{{users.data.length}} tài khoản</small></div><span class="role-pill"><i class="bi bi-shield-check"/> Đang quản lý</span></div><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Họ tên</th><th>Email</th><th>Điện thoại</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="u in users.data" :key="u.id"><td><strong>{{u.name}}</strong></td><td>{{u.email}}</td><td>{{u.phone||'—'}}</td><td><span :class="['badge',u.is_active?'text-bg-success':'text-bg-secondary']">{{u.is_active?'Hoạt động':'Đã khóa'}}</span></td></tr><tr v-if="!users.data.length"><td colspan="4" class="text-center text-secondary py-5">Chưa có tài khoản.</td></tr></tbody></table></div></section>
<section v-if="pendingRequests.length" class="panel mt-3"><div class="panel-title"><div><strong>Yêu cầu chờ Admin phê duyệt</strong><small>Những yêu cầu được tạo từ quy trình nội bộ.</small></div></div><div class="request-grid"><article v-for="r in pendingRequests" :key="r.id"><strong>{{r.name}}</strong><small>{{r.email}} · {{r.phone||'Chưa có SĐT'}}</small><small>Người tạo: {{r.requester?.name||'—'}}</small><div><Form :action="`/admin/backoffice-requests/${r.id}/approve`" method="patch"><button class="btn btn-success btn-sm">Phê duyệt</button></Form><Form :action="`/admin/backoffice-requests/${r.id}/reject`" method="patch"><button class="btn btn-outline-danger btn-sm">Từ chối</button></Form></div></article></div></section>
</div></template>
<style scoped>.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:20px}.head span{color:#2563eb;font-size:.65rem;font-weight:900;letter-spacing:.1em}.head h1{margin:4px 0;font-weight:900}.head p{margin:0;color:#667085;font-size:.75rem}.panel{padding:20px;border:1px solid #e4e7ec;border-radius:18px;background:#fff;box-shadow:0 10px 30px rgba(16,24,40,.04)}.panel-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.panel-title strong,.panel-title small{display:block}.panel-title strong{font-size:13px}.panel-title small{margin-top:3px;color:#98a2b3;font-size:10px}.role-pill{display:inline-flex;align-items:center;gap:5px;padding:7px 10px;border-radius:999px;background:#eff6ff;color:#2563eb;font-size:9px;font-weight:800}.admin-table{margin:0}.admin-table th{font-size:.68rem;color:#667085;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.78rem;border-color:#f2f4f7}.request-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.request-grid article{display:grid;gap:5px;padding:14px;border-radius:12px;background:#f8fafc}.request-grid small{color:#667085;font-size:.65rem}.request-grid article>div{display:flex;gap:7px;margin-top:6px}@media(max-width:700px){.request-grid{grid-template-columns:1fr}}
</style>
