<script setup lang="ts">
import { Form } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
type U={id:number;name:string;email:string;phone?:string;is_active:boolean}; type R={id:number;name:string;email:string;phone?:string;requester?:{name:string};createdAt:string};
const p=defineProps<{role:string;roleLabel:string;users:{data:U[]};pendingRequests:R[]}>(); const open=ref(false); const reject=ref<R|null>(null); const desc=computed(()=>({sales:'Bán hàng và vận hành đơn hàng.',technical:'Sản phẩm, tồn kho và hỗ trợ kỹ thuật.',customer_service:'Chăm sóc khách hàng và hỗ trợ sau bán.'}[p.role]??''));
</script>
<template><div class="admin-page"><header class="head"><div><span>NHÂN SỰ · {{roleLabel.toUpperCase()}}</span><h1>{{roleLabel}}</h1><p>{{desc}}</p></div><button class="btn btn-primary" @click="open=true"><i class="bi bi-person-plus me-2"/>Tạo tài khoản</button></header><section class="panel"><div class="d-flex justify-content-between mb-3"><strong>Tài khoản</strong><small>{{users.data.length}} tài khoản</small></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Họ tên</th><th>Email</th><th>Điện thoại</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="u in users.data" :key="u.id"><td><strong>{{u.name}}</strong></td><td>{{u.email}}</td><td>{{u.phone||'—'}}</td><td>{{u.is_active?'Hoạt động':'Đã khóa'}}</td></tr><tr v-if="!users.data.length"><td colspan="4" class="text-center text-secondary py-5">Chưa có tài khoản.</td></tr></tbody></table></div></section><section v-if="pendingRequests.length" class="panel mt-3"><h3>Yêu cầu chờ Admin phê duyệt</h3><div class="request-grid"><article v-for="r in pendingRequests" :key="r.id"><strong>{{r.name}}</strong><small>{{r.email}} · {{r.phone||'Chưa có SĐT'}}</small><small>Người tạo: {{r.requester?.name||'—'}}</small><div><Form :action="`/admin/backoffice-requests/${r.id}/approve`" method="patch"><button class="btn btn-success btn-sm">Phê duyệt</button></Form><button class="btn btn-outline-danger btn-sm" @click="reject=r">Từ chối</button></div></article></div></section><div v-if="open" class="overlay" @click.self="open=false"><section class="modal"><header><h2>Tạo {{roleLabel}}</h2><button @click="open=false">×</button></header><Form action="/admin/backoffice-requests" method="post" v-slot="{errors,processing}" @success="open=false"><input type="hidden" name="role" :value="role"/><label>Họ và tên</label><input name="name" required/><label>Email</label><input name="email" type="email" required/><label>Số điện thoại</label><input name="phone"/><label>Mật khẩu đăng nhập</label><input name="password" type="password" minlength="8" required/><label>Mật khẩu xác thực quản trị</label><input name="admin_password" type="password" required/><div v-if="errors" class="text-danger small">{{Object.values(errors)[0]}}</div><footer><button type="button" class="btn btn-light" @click="open=false">Hủy</button><button class="btn btn-primary" :disabled="processing">Xác nhận</button></footer></Form></section></div><div v-if="reject" class="overlay" @click.self="reject=null"><section class="modal"><h2>Từ chối yêu cầu</h2><Form :action="`/admin/backoffice-requests/${reject.id}/reject`" method="patch" @success="reject=null"><label>Lý do</label><textarea name="reason" rows="3"/><footer><button type="button" class="btn btn-light" @click="reject=null">Hủy</button><button class="btn btn-danger">Từ chối</button></footer></Form></section></div></div></template>
<style scoped>.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.head span,.panel h3{color:#2563eb;font-size:.65rem;font-weight:900;letter-spacing:.1em}.head h1{margin:4px 0;font-weight:900}.head p{margin:0;color:#667085;font-size:.75rem}.panel{padding:20px;border:1px solid #e4e7ec;border-radius:18px;background:#fff}.request-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.request-grid article{display:grid;gap:5px;padding:13px;border-radius:12px;background:#f8fafc}.request-grid small{color:#667085;font-size:.65rem}.request-grid article>div{display:flex;gap:7px;margin-top:6px}.overlay{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.55)}.modal{width:min(100%,520px);max-height:90vh;overflow:auto;padding:22px;border-radius:20px;background:#fff;box-shadow:0 25px 70px rgba(15,23,42,.25)}.modal header,.modal footer{display:flex;justify-content:space-between;align-items:center;gap:8px}.modal header{margin-bottom:15px}.modal h2{font-size:1.15rem;font-weight:900}.modal header button{border:0;background:none;font-size:24px}.modal label{display:block;margin:10px 0 5px;font-size:.7rem;font-weight:800}.modal input,.modal textarea{width:100%;padding:10px;border:1px solid #dfe4ec;border-radius:9px}.modal footer{justify-content:flex-end;margin-top:16px}@media(max-width:700px){.head,.request-grid{grid-template-columns:1fr;display:grid}}
</style>
