<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';

type Coupon={id:number;code:string;type:string;value:number;min_order_amount:number;max_discount_amount:number|null;usage_limit:number|null;used_count:number;starts_at:string|null;ends_at:string|null;is_active:boolean};
const props=defineProps<{coupons:Coupon[]}>();
const show=ref(false);const form=ref({code:'',type:'percent',value:10,min_order_amount:0,max_discount_amount:'',usage_limit:'',starts_at:'',ends_at:''});
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+' ₫';
function submit(){router.post('/admin/coupons',form.value,{onSuccess:()=>show.value=false});}
</script>
<template><div class="admin-page"><div class="admin-page-head"><div><div class="admin-kicker">KHUYẾN MÃI</div><h1>Quản lý mã giảm giá</h1><p>Tạo và theo dõi mã ưu đãi cho khách hàng.</p></div><button class="btn btn-primary" @click="show=true"><i class="bi bi-plus-lg me-2"/>Thêm mã giảm giá</button></div><div class="admin-panel"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Mã</th><th>Ưu đãi</th><th>Đơn tối thiểu</th><th>Sử dụng</th><th>Thời gian</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="c in props.coupons" :key="c.id"><td class="fw-bold">{{c.code}}</td><td>{{c.type==='percent'?c.value+'%':'-'+money(c.value)}}</td><td>{{money(c.min_order_amount)}}</td><td>{{c.used_count}}{{c.usage_limit?' / '+c.usage_limit:''}}</td><td><span class="small">{{c.starts_at||'Không giới hạn'}}<br/>{{c.ends_at||''}}</span></td><td><span :class="['badge',c.is_active?'text-bg-success':'text-bg-secondary']">{{c.is_active?'Đang hoạt động':'Đã khóa'}}</span></td></tr><tr v-if="!props.coupons.length"><td colspan="6" class="text-center py-5 text-secondary">Chưa có mã giảm giá.</td></tr></tbody></table></div></div><div v-if="show" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow-lg"><div class="modal-header"><h5>Thêm mã giảm giá</h5><button class="btn-close" @click="show=false"/></div><form @submit.prevent="submit"><div class="modal-body"><label class="form-label">Mã giảm giá</label><input v-model="form.code" required class="form-control text-uppercase mb-3"/><div class="row g-3"><div class="col-5"><label class="form-label">Loại</label><select v-model="form.type" class="form-select"><option value="percent">Phần trăm</option><option value="fixed">Số tiền</option></select></div><div class="col-7"><label class="form-label">Giá trị</label><input v-model.number="form.value" type="number" min="1" required class="form-control"/></div><div class="col-12"><label class="form-label">Đơn tối thiểu</label><input v-model.number="form.min_order_amount" type="number" min="0" class="form-control"/></div><div class="col-6"><label class="form-label">Giảm tối đa</label><input v-model="form.max_discount_amount" type="number" min="0" class="form-control"/></div><div class="col-6"><label class="form-label">Giới hạn lượt dùng</label><input v-model="form.usage_limit" type="number" min="1" class="form-control"/></div><div class="col-6"><label class="form-label">Bắt đầu</label><input v-model="form.starts_at" type="datetime-local" class="form-control"/></div><div class="col-6"><label class="form-label">Kết thúc</label><input v-model="form.ends_at" type="datetime-local" class="form-control"/></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="show=false">Hủy</button><button class="btn btn-primary">Tạo mã</button></div></form></div></div></div></div></template>
<style scoped>.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}.admin-modal-backdrop{background:rgba(15,23,42,.45)}</style>