<script setup lang="ts">
import { Link } from '@inertiajs/vue3';

type StatProps = { orders: number; revenue: number; customers: number; products: number };
type ChartProps = { months: string[]; orders: number[]; revenue: number[] };
type RecentOrder = { id: number; code: string; customer_name: string; status: string; total: number; created_at: string };
const props = defineProps<{ stats: StatProps; charts: ChartProps; recentOrders: RecentOrder[] }>();
const money = (n: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(n);
const maxOrders = Math.max(1, ...props.charts.orders);
const maxRevenue = Math.max(1, ...props.charts.revenue);
const shortRevenue = (n: number) => n >= 1000000000 ? `${(n / 1000000000).toFixed(1)} tỷ` : n >= 1000000 ? `${(n / 1000000).toFixed(0)} tr` : money(n);
</script>
<template>
<div class="admin-page"><div class="admin-page-head"><div><div class="admin-kicker">TỔNG QUAN</div><h1>Dashboard quản trị</h1><p>Theo dõi đơn hàng, doanh thu, khách hàng và sản phẩm.</p></div><Link href="/admin/products" class="btn btn-primary"><i class="bi bi-plus-lg me-2"/>Thêm sản phẩm</Link></div>
<div class="row g-3 mb-4"><div class="col-12 col-sm-6 col-xl-3"><div class="stat-card p-4 h-100"><i class="bi bi-receipt stat-icon"/><div class="small text-secondary mt-3">Tổng đơn hàng</div><div class="fs-3 fw-bold">{{props.stats.orders.toLocaleString('vi-VN')}}</div></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="stat-card p-4 h-100"><i class="bi bi-cash-stack stat-icon"/><div class="small text-secondary mt-3">Tổng doanh thu</div><div class="fs-3 fw-bold">{{shortRevenue(props.stats.revenue)}}</div></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="stat-card p-4 h-100"><i class="bi bi-people stat-icon"/><div class="small text-secondary mt-3">Tổng khách hàng</div><div class="fs-3 fw-bold">{{props.stats.customers.toLocaleString('vi-VN')}}</div></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="stat-card p-4 h-100"><i class="bi bi-box-seam stat-icon"/><div class="small text-secondary mt-3">Tổng sản phẩm</div><div class="fs-3 fw-bold">{{props.stats.products.toLocaleString('vi-VN')}}</div></div></div></div>
<div class="row g-4"><div class="col-xl-6"><div class="admin-panel p-4 h-100"><div class="mb-4"><h5 class="fw-bold mb-1">Số lượng đơn hàng</h5><div class="small text-secondary">Theo tháng trong năm {{new Date().getFullYear()}}</div></div><div class="bar-chart"><div v-for="(value,index) in props.charts.orders" :key="props.charts.months[index]" class="bar-item"><div class="bar-value">{{value}}</div><div class="bar-track"><div class="bar-fill" :style="{height:`${Math.max(5,(value/maxOrders)*100)}%`}"/></div><div class="bar-label">{{props.charts.months[index]}}</div></div></div></div></div><div class="col-xl-6"><div class="admin-panel p-4 h-100"><div class="mb-4"><h5 class="fw-bold mb-1">Doanh thu theo tháng</h5><div class="small text-secondary">Tổng giá trị đơn hàng đã ghi nhận</div></div><div class="bar-chart"><div v-for="(value,index) in props.charts.revenue" :key="props.charts.months[index]" class="bar-item"><div class="bar-value">{{shortRevenue(value)}}</div><div class="bar-track revenue"><div class="bar-fill revenue-fill" :style="{height:`${Math.max(5,(value/maxRevenue)*100)}%`}"/></div><div class="bar-label">{{props.charts.months[index]}}</div></div></div></div></div><div class="col-12"><div class="admin-panel p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="fw-bold mb-1">Đơn hàng gần đây</h5><div class="small text-secondary">Danh sách mới nhất cần quản lý</div></div><Link href="/admin/orders" class="btn btn-sm btn-outline-primary">Xem tất cả</Link></div><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Ngày đặt</th><th>Tổng tiền</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="o in props.recentOrders" :key="o.id"><td class="fw-semibold">{{o.code}}</td><td>{{o.customer_name}}</td><td>{{new Date(o.created_at).toLocaleString('vi-VN')}}</td><td class="fw-semibold">{{money(o.total)}}</td><td><span :class="['badge',o.status==='Chờ xử lý'?'text-bg-warning':o.status==='Đã duyệt'?'text-bg-success':'text-bg-secondary']">{{o.status}}</span></td></tr><tr v-if="!props.recentOrders.length"><td colspan="5" class="text-center py-4 text-secondary">Chưa có đơn hàng.</td></tr></tbody></table></div></div></div></div></div>
</template>
<style scoped>.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.stat-card{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.stat-icon{display:grid;width:44px;height:44px;place-items:center;border-radius:12px;color:#2563eb;background:#eff6ff;font-size:1.1rem}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.bar-chart{height:290px;display:flex;align-items:stretch;gap:8px;padding-top:28px}.bar-item{flex:1;display:flex;min-width:0;flex-direction:column;align-items:center}.bar-value{height:26px;max-width:100%;overflow:hidden;color:#667085;font-size:.56rem;font-weight:800;white-space:nowrap;text-overflow:ellipsis}.bar-track{height:235px;width:100%;display:flex;align-items:flex-end;justify-content:center;padding:0 4px;background:linear-gradient(to top,rgba(37,99,235,.06) 1px,transparent 1px);background-size:100% 25%}.bar-fill{width:100%;max-width:38px;border-radius:7px 7px 2px 2px;background:#2563eb;transition:height .3s ease}.revenue-fill{background:#111827}.bar-label{margin-top:8px;color:#98a2b3;font-size:.62rem;font-weight:800}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}@media(max-width:767px){.admin-page-head{align-items:flex-start;flex-direction:column}.bar-chart{gap:3px}.bar-value{font-size:.48rem}.bar-fill{max-width:24px}}</style>
