<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';
type Employee={id:number;name:string;email:string;phone:string|null;role:string;role_label:string;is_active:boolean;approval_status:string;created_at:string;creator:{id:number;name:string}|null};
type RoleOption={value:string;label:string};
const props=defineProps<{users:{data:Employee[];total:number};currentRole:'admin'|'senior_staff';roleOptions:RoleOption[]}>();
const show=ref(false),editing=ref<Employee|null>(null);const form=ref({name:'',email:'',phone:'',password:'',role:props.roleOptions[0]?.value??''});
function reset(){editing.value=null;form.value={name:'',email:'',phone:'',password:'',role:props.roleOptions[0]?.value??''};show.value=true}
function edit(e:Employee){editing.value=e;form.value={name:e.name,email:e.email,phone:e.phone??'',password:'',role:e.role};show.value=true}
function save(){const data={name:form.value.name,email:form.value.email,phone:form.value.phone,password:form.value.password||undefined,role:form.value.role};if(editing.value)router.patch(`/admin/employees/${editing.value.id}`,data,{onSuccess:()=>show.value=false});else router.post('/admin/employees',data,{onSuccess:()=>show.value=false})}
function remove(e:Employee){if(confirm(`Xóa nhân viên ${e.name}?`))router.delete(`/admin/employees/${e.id}`)}
function toggle(e:Employee){if(e.approval_status!=='pending')router.patch(`/admin/employees/${e.id}/toggle`,{})}
function approve(e:Employee){if(confirm(`Phê duyệt ${e.name}?`))router.patch(`/admin/employees/${e.id}/approve`,{})}
function reject(e:Employee){if(confirm(`Từ chối ${e.name}?`))router.patch(`/admin/employees/${e.id}/reject`,{})}
const status=(e:Employee)=>e.approval_status==='pending'?'Chờ phê duyệt':e.approval_status==='rejected'?'Từ chối':e.is_active?'Đang hoạt động':'Đã khóa';
</script>
<template><div class="admin-page"><div class="employee-hero"><div><div class="admin-kicker">HỆ THỐNG</div><h1>Nhân viên cấp cao</h1><p>{{props.currentRole==='admin'?'Quản lý toàn bộ nhân viên trong hệ thống.':'Tạo nhân viên theo 9 chức vụ. Tài khoản mới phải được Quản trị viên phê duyệt.'}}</p></div><button class="btn btn-primary employee-create" @click="reset">Tạo nhân viên</button></div>
<div class="employee-flow"><div class="flow-step"><b>01</b><span>Tạo nhân viên</span></div><i class="bi bi-chevron-right"/><div class="flow-step"><b>02</b><span>Chờ phê duyệt</span></div><i class="bi bi-chevron-right"/><div class="flow-step"><b>03</b><span>Được kích hoạt</span></div></div>
<div class="admin-panel overflow-hidden"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Nhân viên</th><th>Chức vụ</th><th>Người tạo</th><th>Trạng thái</th><th>Ngày tạo</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="e in props.users.data" :key="e.id"><td><strong>{{e.name}}</strong><small>{{e.email}}<span v-if="e.phone"> • {{e.phone}}</span></small></td><td><span class="role-chip">{{e.role_label}}</span></td><td>{{e.creator?.name??'Hệ thống'}}</td><td><span :class="['employee-status',e.approval_status==='pending'?'pending':e.approval_status==='rejected'?'rejected':e.is_active?'active':'inactive']">{{status(e)}}</span></td><td>{{new Date(e.created_at).toLocaleDateString('vi-VN')}}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary me-1" @click="edit(e)">Sửa</button><button v-if="props.currentRole==='admin'&&e.approval_status==='pending'" class="btn btn-sm btn-success me-1" @click="approve(e)">Phê duyệt</button><button v-if="props.currentRole==='admin'&&e.approval_status==='pending'" class="btn btn-sm btn-outline-danger me-1" @click="reject(e)">Từ chối</button><button class="btn btn-sm btn-outline-secondary me-1" @click="toggle(e)" :disabled="e.approval_status==='pending'">{{e.is_active?'Khóa':'Mở khóa'}}</button><button class="btn btn-sm btn-outline-danger" @click="remove(e)">Xóa</button></td></tr><tr v-if="!props.users.data.length"><td colspan="6" class="empty-state">Chưa có nhân viên.</td></tr></tbody></table></div></div>
<div v-if="show" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content employee-modal"><div class="modal-header"><div><div class="modal-kicker">HỒ SƠ NHÂN SỰ</div><h5>{{editing?'Sửa nhân viên':'Tạo nhân viên'}}</h5></div><button class="btn-close" @click="show=false"/></div><form @submit.prevent="save"><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Họ tên</label><input v-model="form.name" class="form-control" required/></div><div class="col-md-6"><label class="form-label">Email</label><input v-model="form.email" type="email" class="form-control" required/></div><div class="col-md-6"><label class="form-label">Số điện thoại</label><input v-model="form.phone" class="form-control"/></div><div class="col-md-6"><label class="form-label">Mật khẩu <span v-if="editing">(bỏ trống nếu không đổi)</span></label><input v-model="form.password" type="password" class="form-control" :required="!editing" minlength="8" autocomplete="new-password"/></div><div class="col-12"><label class="form-label">Chức vụ nhân viên</label><select v-model="form.role" class="form-select" required><option v-for="r in props.roleOptions" :key="r.value" :value="r.value">{{r.label}}</option></select></div></div><div v-if="!editing&&props.currentRole==='senior_staff'" class="notice-box mt-3"><i class="bi bi-hourglass-split"/> Nhân viên sẽ ở trạng thái Chờ phê duyệt cho đến khi Quản trị viên xác nhận.</div><div v-if="!editing&&props.currentRole==='admin'" class="notice-box mt-3"><i class="bi bi-check-circle"/> Nhân viên do Quản trị viên tạo được kích hoạt ngay.</div></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="show=false">Hủy</button><button class="btn btn-primary">{{editing?'Lưu thay đổi':'Tạo nhân viên'}}</button></div></form></div></div></div></div></template>
<style scoped>
.employee-hero{display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:18px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.employee-hero h1{margin:3px 0;font-size:1.8rem;font-weight:900}.employee-hero p{margin:0;color:#667085;font-size:.8rem}.employee-create{min-height:42px;border-radius:11px;font-weight:800}.employee-flow{display:flex;align-items:center;gap:12px;padding:14px 16px;margin-bottom:18px;border:1px solid #e5e9f0;border-radius:15px;background:#fff}.employee-flow>i{color:#98a2b3}.flow-step{display:flex;align-items:center;gap:9px}.flow-step b{display:grid;width:29px;height:29px;place-items:center;border-radius:9px;background:#eff6ff;color:#2563eb;font-size:9px}.flow-step span{font-size:.72rem;font-weight:800}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.68rem;color:#667085;text-transform:uppercase;background:#f8fafc}.admin-table td{font-size:.78rem;border-color:#f2f4f7}.admin-table strong,.admin-table small{display:block}.admin-table small{margin-top:2px;color:#98a2b3;font-size:.61rem}.role-chip{display:inline-flex;padding:6px 9px;border-radius:999px;background:#f5f3ff;color:#5b21b6;font-size:.64rem;font-weight:800}.employee-status{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:.63rem;font-weight:800}.employee-status.active{background:#ecfdf3;color:#15803d}.employee-status.inactive{background:#f2f4f7;color:#667085}.employee-status.pending{background:#fffbeb;color:#b45309}.employee-status.rejected{background:#fef2f2;color:#b91c1c}.empty-state{text-align:center;padding:48px!important;color:#98a2b3}.admin-modal-backdrop{background:rgba(15,23,42,.5);backdrop-filter:blur(4px)}.employee-modal{border:0;border-radius:20px;overflow:hidden}.modal-kicker{color:#4f46e5;font-size:8px;font-weight:900;letter-spacing:.14em;margin-bottom:3px}.notice-box{display:flex;align-items:center;gap:10px;padding:11px 13px;border:1px solid #dbeafe;border-radius:12px;background:#eff6ff;color:#1d4ed8;font-size:.72rem;font-weight:700}@media(max-width:767px){.employee-hero{align-items:stretch;flex-direction:column}.employee-create{align-self:flex-start}.employee-flow{overflow:auto}.flow-step{flex:0 0 auto}}
</style>
