<script setup lang="ts">
import { computed, ref } from 'vue';
import { Link } from '@inertiajs/vue3';

type Product = { id:number; name:string; sku:string; image:string|null; category:string; stock:number; sold:number; price:number; is_active:boolean };
const props = defineProps<{ products:Product[]; summary:{stockUnits:number;soldUnits:number;stockValue:number;lowStock:number} }>();
const search=ref(''); const filter=ref('all');
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);
const rows=computed(()=>props.products.filter(p=>`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(search.value.toLowerCase())).filter(p=>filter.value==='all'||(filter.value==='low'&&p.stock<10)||(filter.value==='out'&&p.stock===0)));
</script>
<template>
<div class="admin-page">
  <div class="admin-page-head"><div><div class="admin-kicker">KHO HÀNG</div><h1>Tồn kho & hàng đã bán</h1><p>Theo dõi số lượng đã bán, tồn thực tế và giá trị hàng đang nằm trong kho.</p></div><Link href="/admin/products" class="btn btn-primary"><i class="bi bi-box-seam me-2"/>Quản lý sản phẩm</Link></div>
  <div class="row g-3 mb-4">
    <div class="col-12 col-sm-6 col-xl-3"><div class="inventory-stat"><span class="stat-dot blue"><i class="bi bi-boxes"/></span><div><span>Tồn kho hiện tại</span><strong>{{props.summary.stockUnits.toLocaleString('vi-VN')}}</strong><small>đơn vị sản phẩm</small></div></div></div>
    <div class="col-12 col-sm-6 col-xl-3"><div class="inventory-stat"><span class="stat-dot green"><i class="bi bi-cart-check"/></span><div><span>Đã bán</span><strong>{{props.summary.soldUnits.toLocaleString('vi-VN')}}</strong><small>theo đơn đã duyệt</small></div></div></div>
    <div class="col-12 col-sm-6 col-xl-3"><div class="inventory-stat"><span class="stat-dot purple"><i class="bi bi-cash-stack"/></span><div><span>Giá trị tồn kho</span><strong>{{money(props.summary.stockValue)}}</strong><small>theo giá bán hiện tại</small></div></div></div>
    <div class="col-12 col-sm-6 col-xl-3"><div class="inventory-stat"><span class="stat-dot red"><i class="bi bi-exclamation-triangle"/></span><div><span>Sắp hết hàng</span><strong>{{props.summary.lowStock}}</strong><small>sản phẩm dưới 10 đơn vị</small></div></div></div>
  </div>
  <div class="admin-panel p-3 mb-3"><div class="row g-2"><div class="col-lg-8"><div class="search-box"><i class="bi bi-search"/><input v-model="search" placeholder="Tìm tên sản phẩm, SKU, danh mục..."/></div></div><div class="col-lg-4"><div class="filter-tabs"><button :class="{active:filter==='all'}" @click="filter='all'">Tất cả</button><button :class="{active:filter==='low'}" @click="filter='low'">Sắp hết</button><button :class="{active:filter==='out'}" @click="filter='out'">Hết hàng</button></div></div></div></div>
  <div class="admin-panel overflow-hidden"><div class="table-responsive"><table class="table admin-table inventory-table align-middle"><thead><tr><th>Sản phẩm</th><th>Danh mục</th><th class="text-center">Đã bán</th><th class="text-center">Tồn kho</th><th>Giá trị tồn</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="p in rows" :key="p.id"><td><div class="product-line"><div class="product-thumb"><img v-if="p.image" :src="p.image" alt=""/><i v-else class="bi bi-image"/></div><div><strong>{{p.name}}</strong><span>{{p.sku}}</span></div></div></td><td>{{p.category}}</td><td class="text-center"><span class="sold-pill">{{p.sold.toLocaleString('vi-VN')}}</span></td><td class="text-center"><span :class="['stock-number',p.stock===0?'out':p.stock<10?'low':'ok']">{{p.stock.toLocaleString('vi-VN')}}</span></td><td class="fw-semibold">{{money(p.stock*p.price)}}</td><td><span :class="['stock-status',p.stock===0?'out':p.stock<10?'low':'ok']">{{p.stock===0?'Hết hàng':p.stock<10?'Sắp hết':'Đủ hàng'}}</span></td></tr><tr v-if="!rows.length"><td colspan="6" class="empty-state">Không có sản phẩm phù hợp.</td></tr></tbody></table></div></div>
</div>
</template>
<style scoped>
.inventory-stat{height:100%;display:flex;gap:14px;align-items:center;padding:20px;border:1px solid #e8ecf3;border-radius:18px;background:#fff;box-shadow:0 10px 30px rgba(15,23,42,.05)}.inventory-stat>div{min-width:0}.inventory-stat span:not(.stat-dot){display:block;color:#667085;font-size:.74rem;font-weight:700}.inventory-stat strong{display:block;margin-top:2px;color:#101828;font-size:1.35rem;line-height:1.2}.inventory-stat small{color:#98a2b3;font-size:.65rem}.stat-dot{display:grid;flex:0 0 46px;width:46px;height:46px;place-items:center;border-radius:14px;font-size:1.1rem}.stat-dot.blue{color:#2563eb;background:#eff6ff}.stat-dot.green{color:#16a34a;background:#f0fdf4}.stat-dot.purple{color:#7c3aed;background:#f5f3ff}.stat-dot.red{color:#dc2626;background:#fef2f2}.search-box{height:42px;display:flex;align-items:center;gap:10px;padding:0 13px;border:1px solid #dfe4ec;border-radius:11px;background:#f8fafc}.search-box i{color:#98a2b3}.search-box input{width:100%;border:0;outline:0;background:transparent;font-size:.8rem}.filter-tabs{height:42px;display:flex;justify-content:flex-end;gap:4px}.filter-tabs button{border:0;border-radius:10px;padding:0 13px;background:transparent;color:#667085;font-size:.72rem;font-weight:800}.filter-tabs button.active{background:#eff6ff;color:#2563eb}.product-line{display:flex;align-items:center;gap:12px}.product-line>div:last-child{display:flex;flex-direction:column}.product-line strong{font-size:.8rem}.product-line span{color:#98a2b3;font-size:.65rem;margin-top:2px}.product-thumb{width:44px;height:44px;display:grid;place-items:center;overflow:hidden;border-radius:11px;background:#f2f4f7;color:#98a2b3}.product-thumb img{width:100%;height:100%;object-fit:cover}.sold-pill{display:inline-flex;min-width:42px;justify-content:center;padding:5px 9px;border-radius:999px;background:#f0fdf4;color:#15803d;font-size:.7rem;font-weight:800}.stock-number{font-weight:900}.stock-number.ok{color:#15803d}.stock-number.low{color:#d97706}.stock-number.out{color:#dc2626}.stock-status{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:.65rem;font-weight:800}.stock-status.ok{background:#ecfdf3;color:#15803d}.stock-status.low{background:#fffbeb;color:#b45309}.stock-status.out{background:#fef2f2;color:#b91c1c}.empty-state{text-align:center;padding:50px!important;color:#98a2b3}.inventory-table td{white-space:nowrap}@media(max-width:767px){.filter-tabs{justify-content:flex-start}.inventory-stat strong{font-size:1.15rem}}
</style>
