<script setup lang="ts">
import { router, Link } from '@inertiajs/vue3';
type Order={id:number;code:string;customer_name:string;status:string;total:number;created_at:string;items:any[]};
const props=defineProps<{orders:{data:Order[];current_page:number;last_page:number;total:number}}>();
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+' ₫';
function approve(o:Order){if(confirm(`Duyệt đơn ${o.code}?`)) router.patch(`/admin/orders/${o.id}/approve`,{})}
</script>
<template><div class="admin-page"><div class="admin-page-head"><div><div class="admin-kicker">ĐƠN HÀNG</div><h1>Duyệt đơn hàng</h1><p>Kiểm tra đơn và duyệt các đơn đang chờ xử lý.</p></div><div class="admin-chip"><i class="bi bi-inbox me-2"/>{{props.orders.total}} đơn</div></div><div class="admin-panel"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Ngày đặt</th><th>Tổng tiền</th><th>Trạng thái</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="o in props.orders.data" :key="o.id"><td class="fw-bold">{{o.code}}</td><td>{{o.customer_name}}</td><td>{{new Date(o.created_at).toLocaleString('vi-VN')}}</td><td class="fw-semibold">{{money(o.total)}}</td><td><span :class="['badge',o.status==='Đã duyệt'?'text-bg-success':o.status==='Chờ xử lý'?'text-bg-warning':'text-bg-secondary']">{{o.status}}</span></td><td class="text-end"><button v-if="o.status==='Chờ xử lý'" class="btn btn-sm btn-primary" @click="approve(o)"><i class="bi bi-check2 me-1"/>Duyệt</button><span v-else class="small text-secondary">Đã xử lý</span></td></tr><tr v-if="!props.orders.data.length"><td colspan="6" class="text-center py-5 text-secondary">Chưa có đơn hàng.</td></tr></tbody></table></div></div><div v-if="props.orders.last_page>1" class="d-flex justify-content-center gap-1 mt-3"><Link v-for="p in props.orders.last_page" :key="p" :href="`/admin/orders?page=${p}`" class="btn btn-sm" :class="p===props.orders.current_page?'btn-primary':'btn-light'">{{p}}</Link></div></div></template>
<style scoped>.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.admin-chip{padding:8px 12px;border:1px solid #e5e9f0;border-radius:10px;background:#fff;color:#475467;font-size:.75rem}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}</style>
