<script setup lang="ts">
import { computed, ref } from 'vue';
import { router } from '@inertiajs/vue3';

type Product = { id: number; name: string; sku: string; brand?: string | null; price: number; old_price?: number | null; stock: number; image?: string | null; is_active: boolean; category: { id: number; name: string } };
type Category = { id: number; name: string };
const props = defineProps<{ products: { data: Product[]; current_page: number; last_page: number; total: number }; categories: Category[] }>();
const showForm = ref(false); const editing = ref<Product | null>(null); const search = ref('');
const form = ref<any>({ category_id: '', name: '', sku: '', brand: '', price: 0, old_price: '', stock: 0, image: '', short_description: '', description: '', specs: {} });
const filtered = computed(() => props.products.data.filter(p => `${p.name} ${p.sku} ${p.brand ?? ''}`.toLowerCase().includes(search.value.trim().toLowerCase())));
const money = (n:number) => new Intl.NumberFormat('vi-VN', { style:'currency', currency:'VND', maximumFractionDigits:0 }).format(n);
function openCreate(){ editing.value=null; form.value={category_id: props.categories[0]?.id ?? '', name:'',sku:'',brand:'',price:0,old_price:'',stock:0,image:'',short_description:'',description:'',specs:{}}; showForm.value=true; }
function openEdit(p:Product){ editing.value=p; form.value={category_id:p.category.id,name:p.name,sku:p.sku,brand:p.brand??'',price:p.price,old_price:p.old_price??'',stock:p.stock,image:p.image??'',short_description:'',description:'',specs:{}}; showForm.value=true; }
function submit(){ const options={ onSuccess:()=>showForm.value=false }; editing.value ? router.patch(`/admin/products/${editing.value.id}`, form.value, options) : router.post('/admin/products', form.value, options); }
function toggle(p:Product){ router.patch(`/admin/products/${p.id}/toggle`, {}); }
function pageUrl(page:number){ return `/admin/products?page=${page}`; }
</script>
<template>
<div class="admin-page"><div class="admin-page-head"><div><div class="admin-kicker">SẢN PHẨM</div><h1>Quản lý sản phẩm</h1><p>Thêm, sửa, khóa và kích hoạt sản phẩm.</p></div><button class="btn btn-primary" @click="openCreate"><i class="bi bi-plus-lg me-2"/>Thêm sản phẩm</button></div>
<div class="admin-panel p-3 mb-3"><div class="row g-2"><div class="col-md-8"><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"/></span><input v-model="search" class="form-control" placeholder="Tìm theo tên, mã sản phẩm, thương hiệu..."/></div></div><div class="col-md-4 d-flex justify-content-md-end align-items-center small text-secondary">{{ props.products.total }} sản phẩm</div></div></div>
<div class="admin-panel"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Sản phẩm</th><th>Danh mục</th><th>Giá</th><th>Tồn kho</th><th>Trạng thái</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td><div class="d-flex gap-3 align-items-center"><div class="admin-product-thumb"><img v-if="item.image" :src="item.image" alt=""/></div><div><div class="fw-semibold">{{ item.name }}</div><div class="small text-secondary">{{ item.brand || 'Không rõ' }} · {{ item.sku }}</div></div></div></td><td>{{ item.category.name }}</td><td class="fw-semibold">{{ money(item.price) }}</td><td><span :class="item.stock < 10 ? 'text-danger fw-bold' : ''">{{ item.stock }}</span></td><td><span :class="['badge', item.is_active ? 'text-bg-success' : 'text-bg-secondary']">{{ item.is_active ? 'Đang bán' : 'Đã khóa' }}</span></td><td class="text-end"><div class="btn-group btn-group-sm"><button class="btn btn-outline-primary" @click="openEdit(item)"><i class="bi bi-pencil"/></button><button class="btn btn-outline-secondary" @click="toggle(item)"><i :class="['bi', item.is_active ? 'bi-lock' : 'bi-unlock']"/></button></div></td></tr><tr v-if="!filtered.length"><td colspan="6" class="text-center py-5 text-secondary">Không có sản phẩm phù hợp.</td></tr></tbody></table></div>
<div v-if="props.products.last_page>1" class="d-flex justify-content-center gap-1 p-3 border-top"><Link v-for="p in props.products.last_page" :key="p" :href="pageUrl(p)" class="btn btn-sm" :class="p===props.products.current_page?'btn-primary':'btn-light'">{{p}}</Link></div></div>
<div v-if="showForm" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content border-0 shadow-lg"><div class="modal-header"><h5>{{ editing ? 'Cập nhật sản phẩm' : 'Thêm sản phẩm' }}</h5><button class="btn-close" @click="showForm=false"/></div><form @submit.prevent="submit"><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Tên sản phẩm</label><input v-model="form.name" required class="form-control"/></div><div class="col-md-4"><label class="form-label">Mã SKU</label><input v-model="form.sku" required class="form-control"/></div><div class="col-md-6"><label class="form-label">Danh mục</label><select v-model="form.category_id" required class="form-select"><option v-for="c in props.categories" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div class="col-md-3"><label class="form-label">Thương hiệu</label><input v-model="form.brand" class="form-control"/></div><div class="col-md-3"><label class="form-label">Tồn kho</label><input v-model.number="form.stock" type="number" min="0" class="form-control"/></div><div class="col-md-6"><label class="form-label">Giá bán</label><input v-model.number="form.price" type="number" min="0" class="form-control"/></div><div class="col-md-6"><label class="form-label">Giá niêm yết</label><input v-model="form.old_price" type="number" min="0" class="form-control"/></div><div class="col-12"><label class="form-label">Ảnh</label><input v-model="form.image" class="form-control" placeholder="https://..."/></div><div class="col-12"><label class="form-label">Mô tả ngắn</label><textarea v-model="form.short_description" rows="2" class="form-control"/></div><div class="col-12"><label class="form-label">Mô tả chi tiết</label><textarea v-model="form.description" rows="5" class="form-control"/></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="showForm=false">Hủy</button><button class="btn btn-primary">Lưu sản phẩm</button></div></form></div></div></div>
</div>
</template>
<style scoped>.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}.admin-product-thumb{width:48px;height:48px;border-radius:10px;overflow:hidden;background:#f3f5f9;display:grid;place-items:center}.admin-product-thumb img{width:100%;height:100%;object-fit:cover}.admin-modal-backdrop{background:rgba(15,23,42,.45)}@media(max-width:767px){.admin-page-head{align-items:flex-start;flex-direction:column}}</style>
