<script setup lang="ts">
import { Form } from '@inertiajs/vue3';

type R={id:number;status:string;reason:string;customerNote?:string;inspectionNote?:string;refundAmount:number;order?:{code:string;customer_name:string;total:number;status:string};customer?:{name:string;email:string};createdAt?:string};
const p=defineProps<{requests:{data:R[];current_page:number;last_page:number;total:number}}>();
const label=(s:string)=>({customer_requested:'Khách yêu cầu',awaiting_admin:'Chờ Admin duyệt',awaiting_receive:'Chờ nhận hàng hoàn',inspecting:'Đang kiểm tra hàng',refunded:'Đã hoàn tiền',rejected:'Từ chối'}[s]??s);
const cls=(s:string)=>({customer_requested:'pending',awaiting_admin:'review',awaiting_receive:'waiting',inspecting:'checking',refunded:'success',rejected:'danger'}[s]??'waiting');
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(Number(n||0))+' ₫';
const date=(v?:string)=>v?new Date(v).toLocaleString('vi-VN'):'—';
</script>
<template><div class="admin-page"><header class="head"><div><span>HẬU MÃI · ĐỔI TRẢ</span><h1>Trả hàng & hoàn tiền</h1><p>Theo dõi toàn bộ yêu cầu trả hàng từ lúc khách gửi yêu cầu đến khi hoàn tiền hoặc trả hàng lại cho khách.</p></div><div class="count"><strong>{{p.requests.total}}</strong><span>yêu cầu</span></div></header>
<section class="panel"><div class="panel-head"><div><strong>Danh sách yêu cầu trả hàng</strong><small>Quy trình: tiếp nhận → phê duyệt → nhận hàng → kiểm tra → quyết định.</small></div></div><div class="table-wrap"><table class="table align-middle returns-table"><thead><tr><th>Đơn hàng</th><th>Khách hàng</th><th>Lý do</th><th>Hoàn tiền</th><th>Trạng thái</th><th>Thời gian</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="r in p.requests.data" :key="r.id"><td><strong>#{{r.order?.code||'—'}}</strong><small>{{r.order?.status||'—'}}</small></td><td><strong>{{r.customer?.name||r.order?.customer_name||'—'}}</strong><small>{{r.customer?.email||'—'}}</small></td><td><span class="reason">{{r.reason}}</span><small v-if="r.customerNote">Ghi chú: {{r.customerNote}}</small></td><td class="money">{{money(r.refundAmount)}}</td><td><span :class="['status',cls(r.status)]"><i class="bi bi-circle-fill"/>{{label(r.status)}}</span><small v-if="r.inspectionNote">{{r.inspectionNote}}</small></td><td>{{date(r.createdAt)}}</td><td class="text-end"><div class="actions"><Form v-if="r.status==='customer_requested'" :action="`/admin/returns/${r.id}/sales-approve`" method="patch"><button class="btn btn-primary btn-sm">Tiếp nhận</button></Form><Form v-else-if="r.status==='awaiting_admin'" :action="`/admin/returns/${r.id}/admin-approve`" method="patch"><button class="btn btn-success btn-sm">Phê duyệt trả hàng</button></Form><Form v-else-if="r.status==='awaiting_receive'" :action="`/admin/returns/${r.id}/receive`" method="patch"><button class="btn btn-warning btn-sm">Đã nhận hàng · Bắt đầu kiểm tra</button></Form><template v-else-if="r.status==='inspecting'"><Form :action="`/admin/returns/${r.id}/refund`" method="patch"><button class="btn btn-success btn-sm">Phê duyệt hoàn tiền</button></Form><Form :action="`/admin/returns/${r.id}/return-to-customer`" method="patch"><button class="btn btn-outline-danger btn-sm">Từ chối · Trả khách</button></Form></template><Form v-if="['customer_requested','awaiting_admin'].includes(r.status)" :action="`/admin/returns/${r.id}/reject`" method="patch"><button class="btn btn-outline-secondary btn-sm">Từ chối</button></Form></div></td></tr><tr v-if="!p.requests.data.length"><td colspan="7" class="empty">Chưa có yêu cầu trả hàng.</td></tr></tbody></table></div></section></div></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:22px}.head span{color:#2563eb;font-size:.65rem;font-weight:900;letter-spacing:.12em}.head h1{margin:4px 0 6px;font-size:1.7rem;font-weight:900}.head p{margin:0;max-width:760px;color:#667085;font-size:.75rem}.count{display:flex;align-items:baseline;gap:6px;padding:10px 14px;border:1px solid #e4e7ec;border-radius:12px;background:#fff}.count strong{font-size:1.2rem}.count span{color:#667085;font-size:.7rem}.panel{border:1px solid #e4e7ec;border-radius:18px;background:#fff;box-shadow:0 10px 30px rgba(16,24,40,.05);overflow:hidden}.panel-head{padding:18px 20px;border-bottom:1px solid #edf0f4}.panel-head strong,.panel-head small{display:block}.panel-head strong{font-size:13px}.panel-head small{margin-top:4px;color:#98a2b3;font-size:10px}.table-wrap{overflow:auto}.returns-table{min-width:1120px;margin:0}.returns-table th{padding:12px 14px;background:#f8fafc;color:#667085;font-size:.65rem;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap}.returns-table td{padding:14px;border-color:#f0f2f5;font-size:.72rem;vertical-align:middle}.returns-table td strong,.returns-table td small{display:block}.returns-table td small{margin-top:4px;color:#98a2b3;font-size:.61rem}.reason{display:block;max-width:180px;white-space:normal;line-height:1.45}.money{font-weight:900;white-space:nowrap}.status{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;font-size:.61rem;font-weight:800;white-space:nowrap}.status i{font-size:5px}.status.pending{background:#fffaeb;color:#b54708}.status.review{background:#eff6ff;color:#175cd3}.status.waiting{background:#f2f4f7;color:#475467}.status.checking{background:#fff7ed;color:#c2410c}.status.success{background:#ecfdf3;color:#027a48}.status.danger{background:#fef3f2;color:#b42318}.actions{display:flex;justify-content:flex-end;gap:5px;flex-wrap:wrap}.actions button{font-size:.62rem;white-space:nowrap}.empty{text-align:center!important;padding:65px!important;color:#98a2b3}.empty::before{content:'↩';display:block;margin-bottom:8px;font-size:28px;color:#cbd5e1}@media(max-width:800px){.head{align-items:flex-start;flex-direction:column}}
</style>