<script setup lang="ts">
import { Form } from '@inertiajs/vue3';
type R={id:number;status:string;reason:string;customerNote?:string;refundAmount:number;order?:{code:string;customer_name:string;total:number};customer?:{name:string;email:string}};
const p=defineProps<{requests:{data:R[]}}>();
const label=(s:string)=>({customer_requested:'Khách yêu cầu',awaiting_admin:'Chờ Admin duyệt',awaiting_receive:'Chờ nhận hàng',inspected:'Đã kiểm tra · chờ hoàn tiền',refunded:'Đã hoàn tiền'}[s]??s);
</script>
<template><div class="admin-page"><header class="head"><div><span>HẬU MÃI · ĐỔI TRẢ</span><h1>Trả hàng & hoàn tiền</h1><p>Bán hàng → Admin → nhận & kiểm tra hàng → hoàn tiền.</p></div></header><section class="panel"><article v-for="r in requests.data" :key="r.id" class="row"><div><strong>#{{r.order?.code||'—'}} · {{r.customer?.name||r.order?.customer_name||'Khách hàng'}}</strong><span>{{r.reason}}</span><small>{{r.customerNote||'Không có ghi chú'}}</small></div><div><b>{{label(r.status)}}</b><small>Hoàn: {{r.refundAmount.toLocaleString('vi-VN')}} ₫</small></div><div><Form v-if="r.status==='customer_requested'" :action="`/admin/returns/${r.id}/sales-approve`" method="patch"><button class="btn btn-primary btn-sm">Bán hàng tiếp nhận</button></Form><Form v-else-if="r.status==='awaiting_admin'" :action="`/admin/returns/${r.id}/admin-approve`" method="patch"><button class="btn btn-success btn-sm">Admin phê duyệt</button></Form><Form v-else-if="r.status==='awaiting_receive'" :action="`/admin/returns/${r.id}/receive`" method="patch"><input type="hidden" name="inspection_note" value="Đã nhận hàng và kiểm tra đạt yêu cầu."/><button class="btn btn-warning btn-sm">Kiểm tra hàng</button></Form><Form v-else-if="r.status==='inspected'" :action="`/admin/returns/${r.id}/refund`" method="patch"><button class="btn btn-danger btn-sm">Xác nhận hoàn tiền</button></Form></div></article><div v-if="!requests.data.length" class="empty">Chưa có yêu cầu trả hàng.</div></section></div></template>
<style scoped>.head span{color:#2563eb;font-size:.65rem;font-weight:900;letter-spacing:.12em}.head h1{margin:4px 0;font-weight:900}.head p{margin:0;color:#667085;font-size:.75rem}.panel{margin-top:20px;border:1px solid #e4e7ec;border-radius:18px;background:#fff;overflow:hidden}.row{display:grid;grid-template-columns:1.5fr 1fr auto;gap:16px;align-items:center;padding:16px 18px;border-bottom:1px solid #edf0f4}.row:last-child{border:0}.row>div{display:grid;gap:4px}.row span,.row small{color:#667085;font-size:.62rem}.row b{font-size:.65rem}.empty{padding:50px;text-align:center;color:#98a2b3}@media(max-width:800px){.row{grid-template-columns:1fr}}
</style>
