<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';
type Fee={id:number;name:string;province:string|null;fee:number;free_ship_from:number|null;is_active:boolean};
const props=defineProps<{fees:Fee[]}>();const show=ref(false);const editing=ref<Fee|null>(null);const form=ref({name:'',province:'',fee:30000,free_ship_from:''});
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+' ₫';
function openCreate(){editing.value=null;form.value={name:'Toàn quốc',province:'',fee:30000,free_ship_from:''};show.value=true}
function openEdit(f:Fee){editing.value=f;form.value={name:f.name,province:f.province??'',fee:f.fee,free_ship_from:f.free_ship_from??''};show.value=true}
function submit(){const o={onSuccess:()=>show.value=false};editing.value?router.patch(`/admin/shipping/${editing.value.id}`,form.value,o):router.post('/admin/shipping',form.value,o)}
</script>
<template><div class="admin-page"><div class="admin-page-head"><div><div class="admin-kicker">VẬN CHUYỂN</div><h1>Quản lý phí vận chuyển</h1><p>Thiết lập phí giao hàng theo khu vực và ngưỡng miễn phí.</p></div><button class="btn btn-primary" @click="openCreate"><i class="bi bi-plus-lg me-2"/>Thêm cấu hình</button></div><div class="admin-panel"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Cấu hình</th><th>Khu vực</th><th>Phí vận chuyển</th><th>Miễn phí từ</th><th>Trạng thái</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="f in props.fees" :key="f.id"><td class="fw-semibold">{{f.name}}</td><td>{{f.province||'Toàn quốc'}}</td><td>{{money(f.fee)}}</td><td>{{f.free_ship_from?money(f.free_ship_from):'Không áp dụng'}}</td><td><span :class="['badge',f.is_active?'text-bg-success':'text-bg-secondary']">{{f.is_active?'Đang áp dụng':'Đã khóa'}}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" @click="openEdit(f)"><i class="bi bi-pencil"/></button></td></tr><tr v-if="!props.fees.length"><td colspan="6" class="text-center py-5 text-secondary">Chưa có cấu hình phí.</td></tr></tbody></table></div></div><div v-if="show" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow-lg"><div class="modal-header"><h5>{{editing?'Cập nhật cấu hình':'Thêm cấu hình'}}</h5><button class="btn-close" @click="show=false"/></div><form @submit.prevent="submit"><div class="modal-body"><label class="form-label">Tên cấu hình</label><input v-model="form.name" required class="form-control mb-3"/><label class="form-label">Tỉnh / khu vực</label><input v-model="form.province" class="form-control mb-3" placeholder="Để trống = toàn quốc"/><label class="form-label">Phí vận chuyển</label><input v-model.number="form.fee" type="number" min="0" required class="form-control mb-3"/><label class="form-label">Miễn phí từ đơn hàng</label><input v-model="form.free_ship_from" type="number" min="0" class="form-control"/></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="show=false">Hủy</button><button class="btn btn-primary">Lưu</button></div></form></div></div></div></div></template>
<style scoped>.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}.admin-modal-backdrop{background:rgba(15,23,42,.45)}</style>