<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';

type User={id:number;name:string;email:string;phone:string|null;is_active:boolean;created_at:string};
const props=defineProps<{users:{data:User[];current_page:number;last_page:number;total:number};role:'customer'|'staff'}>();
const show=ref(false);const editing=ref<User|null>(null);const form=ref({name:'',email:'',phone:'',password:''});
const title=props.role==='customer'?'Khách hàng':'Nhân viên';
function openCreate(){editing.value=null;form.value={name:'',email:'',phone:'',password:''};show.value=true}
function openEdit(u:User){editing.value=u;form.value={name:u.name,email:u.email,phone:u.phone??'',password:''};show.value=true}
function submit(){if(editing.value){router.patch(`/admin/users/${editing.value.id}`,{name:form.value.name,email:form.value.email,phone:form.value.phone,is_active:editing.value.is_active},{onSuccess:()=>show.value=false})}else{router.post(`/admin/${props.role==='staff'?'employees':'customers'}`,form.value,{onSuccess:()=>show.value=false})}}
function toggle(u:User){router.patch(`/admin/users/${u.id}`,{name:u.name,email:u.email,phone:u.phone,is_active:!u.is_active})}
function remove(u:User){if(confirm(`Xóa tài khoản ${u.name}?`)) router.delete(`/admin/users/${u.id}`)}
</script>
<template><div class="admin-page"><div class="admin-page-head"><div><div class="admin-kicker">HỆ THỐNG</div><h1>Quản lý {{title.toLowerCase()}}</h1><p>Thêm, sửa, xóa và kích hoạt tài khoản.</p></div><button class="btn btn-primary" @click="openCreate"><i class="bi bi-plus-lg me-2"/>Thêm {{title.toLowerCase()}}</button></div><div class="admin-panel"><div class="table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Tài khoản</th><th>Liên hệ</th><th>Ngày tạo</th><th>Trạng thái</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="u in props.users.data" :key="u.id"><td><div class="d-flex align-items-center gap-3"><div class="user-avatar"><i class="bi bi-person-fill"/></div><div><div class="fw-semibold">{{u.name}}</div><div class="small text-secondary">{{u.email}}</div></div></div></td><td>{{u.phone||'Chưa cập nhật'}}</td><td>{{new Date(u.created_at).toLocaleDateString('vi-VN')}}</td><td><span :class="['badge',u.is_active?'text-bg-success':'text-bg-secondary']">{{u.is_active?'Đang hoạt động':'Đã khóa'}}</span></td><td class="text-end"><div class="btn-group btn-group-sm"><button class="btn btn-outline-primary" @click="openEdit(u)"><i class="bi bi-pencil"/></button><button class="btn btn-outline-secondary" @click="toggle(u)"><i :class="['bi',u.is_active?'bi-lock':'bi-unlock']"/></button><button class="btn btn-outline-danger" @click="remove(u)"><i class="bi bi-trash"/></button></div></td></tr><tr v-if="!props.users.data.length"><td colspan="5" class="text-center py-5 text-secondary">Chưa có dữ liệu.</td></tr></tbody></table></div></div><div v-if="show" class="modal d-block admin-modal-backdrop"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 shadow-lg"><div class="modal-header"><h5>{{editing?'Cập nhật':'Thêm'}} {{title.toLowerCase()}}</h5><button class="btn-close" @click="show=false"/></div><form @submit.prevent="submit"><div class="modal-body"><label class="form-label">Họ tên</label><input v-model="form.name" required class="form-control mb-3"/><label class="form-label">Email</label><input v-model="form.email" type="email" required class="form-control mb-3"/><label class="form-label">Số điện thoại</label><input v-model="form.phone" class="form-control mb-3"/><label v-if="!editing" class="form-label">Mật khẩu</label><input v-if="!editing" v-model="form.password" type="password" required minlength="8" class="form-control"/></div><div class="modal-footer"><button type="button" class="btn btn-light" @click="show=false">Hủy</button><button class="btn btn-primary">Lưu</button></div></form></div></div></div></div></template>
<style scoped>.admin-page-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.admin-kicker{color:#2563eb;font-size:.68rem;font-weight:900;letter-spacing:.14em}.admin-page-head h1{margin:3px 0;font-size:1.7rem;font-weight:900}.admin-page-head p{margin:0;color:#667085}.admin-panel{border:1px solid #e5e9f0;border-radius:16px;background:#fff;box-shadow:0 8px 28px rgba(16,24,40,.05)}.admin-table{margin:0}.admin-table th{font-size:.72rem;color:#667085;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid #edf0f4}.admin-table td{font-size:.8rem;border-color:#f2f4f7}.user-avatar{width:40px;height:40px;border-radius:12px;display:grid;place-items:center;color:#2563eb;background:#eff6ff}.admin-modal-backdrop{background:rgba(15,23,42,.45)}</style>
